# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/mygola ./..."
  bin = "tmp/mygola"
  include_ext = ["go","tpl","tmpl","html"]
  exclude_dir = ["assets","tmp","vendor"]
  delay = 1000 # milliseconds
